name: cryptonator_api
description: Library to access Cryptonator (https://www.cryptonator.com/api/) API
version: 0.0.1
homepage: https://github.com/tejainece/cryptonator_api
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3

dev_dependencies:
  test: ^0.12.0
